.TH "_HashTab" 3 "Tue Jun 12 2012" "Version 1.0.0.3164pre" "Notatio Antiqua" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_HashTab \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBHashEntry\fP * \fBentries\fP [\fBHASH_SIZE\fP]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 94 of file hyphen\&.c\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBHashEntry\fP* \fB_HashTab::entries\fP[\fBHASH_SIZE\fP]"
.PP
Definition at line 95 of file hyphen\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Notatio Antiqua from the source code\&.
