.TH "_HyphenState" 3 "Tue Jun 12 2012" "Version 1.0.0.3164pre" "Notatio Antiqua" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_HyphenState \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <hyphen\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char * \fBmatch\fP"
.br
.ti -1c
.RI "char * \fBrepl\fP"
.br
.ti -1c
.RI "signed char \fBreplindex\fP"
.br
.ti -1c
.RI "signed char \fBreplcut\fP"
.br
.ti -1c
.RI "int \fBfallback_state\fP"
.br
.ti -1c
.RI "int \fBnum_trans\fP"
.br
.ti -1c
.RI "\fBHyphenTrans\fP * \fBtrans\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 81 of file hyphen\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "int \fB_HyphenState::fallback_state\fP"
.PP
Definition at line 86 of file hyphen\&.h\&.
.SS "char* \fB_HyphenState::match\fP"
.PP
Definition at line 82 of file hyphen\&.h\&.
.SS "int \fB_HyphenState::num_trans\fP"
.PP
Definition at line 87 of file hyphen\&.h\&.
.SS "char* \fB_HyphenState::repl\fP"
.PP
Definition at line 83 of file hyphen\&.h\&.
.SS "signed char \fB_HyphenState::replcut\fP"
.PP
Definition at line 85 of file hyphen\&.h\&.
.SS "signed char \fB_HyphenState::replindex\fP"
.PP
Definition at line 84 of file hyphen\&.h\&.
.SS "\fBHyphenTrans\fP* \fB_HyphenState::trans\fP"
.PP
Definition at line 88 of file hyphen\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Notatio Antiqua from the source code\&.
