.TH "_HyphenDict" 3 "Tue Jun 12 2012" "Version 1.0.0.3164pre" "Notatio Antiqua" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_HyphenDict \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <hyphen\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBlhmin\fP"
.br
.ti -1c
.RI "char \fBrhmin\fP"
.br
.ti -1c
.RI "char \fBclhmin\fP"
.br
.ti -1c
.RI "char \fBcrhmin\fP"
.br
.ti -1c
.RI "char * \fBnohyphen\fP"
.br
.ti -1c
.RI "int \fBnohyphenl\fP"
.br
.ti -1c
.RI "int \fBnum_states\fP"
.br
.ti -1c
.RI "char \fBcset\fP [\fBMAX_NAME\fP]"
.br
.ti -1c
.RI "int \fButf8\fP"
.br
.ti -1c
.RI "\fBHyphenState\fP * \fBstates\fP"
.br
.ti -1c
.RI "\fBHyphenDict\fP * \fBnextlevel\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 64 of file hyphen\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "char \fB_HyphenDict::clhmin\fP"
.PP
Definition at line 68 of file hyphen\&.h\&.
.SS "char \fB_HyphenDict::crhmin\fP"
.PP
Definition at line 69 of file hyphen\&.h\&.
.SS "char \fB_HyphenDict::cset\fP[\fBMAX_NAME\fP]"
.PP
Definition at line 75 of file hyphen\&.h\&.
.SS "char \fB_HyphenDict::lhmin\fP"
.PP
Definition at line 66 of file hyphen\&.h\&.
.SS "\fBHyphenDict\fP* \fB_HyphenDict::nextlevel\fP"
.PP
Definition at line 78 of file hyphen\&.h\&.
.SS "char* \fB_HyphenDict::nohyphen\fP"
.PP
Definition at line 70 of file hyphen\&.h\&.
.SS "int \fB_HyphenDict::nohyphenl\fP"
.PP
Definition at line 72 of file hyphen\&.h\&.
.SS "int \fB_HyphenDict::num_states\fP"
.PP
Definition at line 74 of file hyphen\&.h\&.
.SS "char \fB_HyphenDict::rhmin\fP"
.PP
Definition at line 67 of file hyphen\&.h\&.
.SS "\fBHyphenState\fP* \fB_HyphenDict::states\fP"
.PP
Definition at line 77 of file hyphen\&.h\&.
.SS "int \fB_HyphenDict::utf8\fP"
.PP
Definition at line 76 of file hyphen\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Notatio Antiqua from the source code\&.
