.TH "_HyphenTrans" 3 "Tue Jun 12 2012" "Version 1.0.0.3164pre" "Notatio Antiqua" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_HyphenTrans \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <hyphen\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBch\fP"
.br
.ti -1c
.RI "int \fBnew_state\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 91 of file hyphen\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "char \fB_HyphenTrans::ch\fP"
.PP
Definition at line 92 of file hyphen\&.h\&.
.SS "int \fB_HyphenTrans::new_state\fP"
.PP
Definition at line 93 of file hyphen\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Notatio Antiqua from the source code\&.
