.TH "Highlighter" 3 "Tue Jun 12 2012" "Version 1.0.0.3164pre" "Notatio Antiqua" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Highlighter \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nasyntax\&.h>\fP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBHighlightingRule\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHighlighter\fP (QTextDocument *parent=0)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBhighlightBlock\fP (const QString &text)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 62 of file nasyntax\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBHighlighter::Highlighter\fP (QTextDocument *parent = \fC0\fP)"
.PP
Definition at line 41 of file nasyntax\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void \fBHighlighter::highlightBlock\fP (const QString &text)\fC [protected]\fP"
.PP
Definition at line 108 of file nasyntax\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Notatio Antiqua from the source code\&.
