.TH "hnjalloc.c" 3 "Tue Jun 12 2012" "Version 1.0.0.3164pre" "Notatio Antiqua" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hnjalloc.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void * \fBhnj_malloc\fP (int size)"
.br
.ti -1c
.RI "void * \fBhnj_realloc\fP (void *p, int size)"
.br
.ti -1c
.RI "void \fBhnj_free\fP (void *p)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void \fBhnj_free\fP (void *p)"
.PP
Definition at line 68 of file hnjalloc\&.c\&.
.SS "void* \fBhnj_malloc\fP (intsize)"
.PP
Definition at line 42 of file hnjalloc\&.c\&.
.SS "void* \fBhnj_realloc\fP (void *p, intsize)"
.PP
Definition at line 56 of file hnjalloc\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Notatio Antiqua from the source code\&.
