.TH "hyphen.h" 3 "Tue Jun 12 2012" "Version 1.0.0.3164pre" "Notatio Antiqua" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hyphen.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fB_HyphenDict\fP"
.br
.ti -1c
.RI "struct \fB_HyphenState\fP"
.br
.ti -1c
.RI "struct \fB_HyphenTrans\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBMAX_CHARS\fP   100"
.br
.ti -1c
.RI "#define \fBMAX_NAME\fP   20"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fB_HyphenDict\fP \fBHyphenDict\fP"
.br
.ti -1c
.RI "typedef struct \fB_HyphenState\fP \fBHyphenState\fP"
.br
.ti -1c
.RI "typedef struct \fB_HyphenTrans\fP \fBHyphenTrans\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBHyphenDict\fP * \fBhnj_hyphen_load\fP (const char *fn)"
.br
.ti -1c
.RI "void \fBhnj_hyphen_free\fP (\fBHyphenDict\fP *dict)"
.br
.ti -1c
.RI "int \fBhnj_hyphen_hyphenate\fP (\fBHyphenDict\fP *dict, const char *word, int word_size, char *hyphens)"
.br
.ti -1c
.RI "int \fBhnj_hyphen_hyphenate2\fP (\fBHyphenDict\fP *dict, const char *word, int word_size, char *hyphens, char *hyphenated_word, char ***rep, int **pos, int **cut)"
.br
.ti -1c
.RI "int \fBhnj_hyphen_hyphenate3\fP (\fBHyphenDict\fP *dict, const char *word, int word_size, char *hyphens, char *hyphword, char ***rep, int **pos, int **cut, int lhmin, int rhmin, int clhmin, int crhmin)"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define \fBMAX_CHARS\fP   100"
.PP
Definition at line 61 of file hyphen\&.h\&.
.SS "#define \fBMAX_NAME\fP   20"
.PP
Definition at line 62 of file hyphen\&.h\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fB_HyphenDict\fP \fBHyphenDict\fP"
.PP
Definition at line 58 of file hyphen\&.h\&.
.SS "typedef struct \fB_HyphenState\fP \fBHyphenState\fP"
.PP
Definition at line 59 of file hyphen\&.h\&.
.SS "typedef struct \fB_HyphenTrans\fP \fBHyphenTrans\fP"
.PP
Definition at line 60 of file hyphen\&.h\&.
.SH "Function Documentation"
.PP 
.SS "void \fBhnj_hyphen_free\fP (\fBHyphenDict\fP *dict)"
.PP
Definition at line 516 of file hyphen\&.c\&.
.SS "int \fBhnj_hyphen_hyphenate\fP (\fBHyphenDict\fP *dict, const char *word, intword_size, char *hyphens)"
.PP
Definition at line 542 of file hyphen\&.c\&.
.SS "int \fBhnj_hyphen_hyphenate2\fP (\fBHyphenDict\fP *dict, const char *word, intword_size, char *hyphens, char *hyphenated_word, char ***rep, int **pos, int **cut)"
.PP
Definition at line 1114 of file hyphen\&.c\&.
.SS "int \fBhnj_hyphen_hyphenate3\fP (\fBHyphenDict\fP *dict, const char *word, intword_size, char *hyphens, char *hyphword, char ***rep, int **pos, int **cut, intlhmin, intrhmin, intclhmin, intcrhmin)"
.PP
Definition at line 1149 of file hyphen\&.c\&.
.SS "\fBHyphenDict\fP* \fBhnj_hyphen_load\fP (const char *fn)"
.PP
Definition at line 375 of file hyphen\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Notatio Antiqua from the source code\&.
