.TH "main.cpp" 3 "Tue Jun 12 2012" "Version 1.0.0.3164pre" "Notatio Antiqua" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QTranslator>\fP
.br
\fC#include <QLocale>\fP
.br
\fC#include <QLibraryInfo>\fP
.br
\fC#include <QFont>\fP
.br
\fC#include 'naprog\&.h'\fP
.br
\fC#include 'version\&.h'\fP
.br
\fC#include 'naapplication\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int \fBmain\fP (intargc, char *argv[])"
.PP
Definition at line 18 of file main\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Notatio Antiqua from the source code\&.
