.TH "naapplication.cpp" 3 "Tue Jun 12 2012" "Version 1.0.0.3164pre" "Notatio Antiqua" \" -*- nroff -*-
.ad l
.nh
.SH NAME
naapplication.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'naapplication\&.h'\fP
.br
\fC#include 'naprog\&.h'\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBnaApp\fP   (static_cast<\fBnaapplication\fP *>(QCoreApplication::instance()))"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define \fBnaApp\fP   (static_cast<\fBnaapplication\fP *>(QCoreApplication::instance()))"
.PP
Definition at line 3 of file naapplication\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Notatio Antiqua from the source code\&.
