.TH "NAClefSelect" 3 "Tue Jun 12 2012" "Version 1.0.0.3164pre" "Notatio Antiqua" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NAClefSelect \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <naclefselect\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNAClefSelect\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "\fB~NAClefSelect\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QString \fBclefS\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 17 of file naclefselect\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBNAClefSelect::NAClefSelect\fP (QWidget *parent = \fC0\fP)\fC [explicit]\fP"
.PP
Definition at line 4 of file naclefselect\&.cpp\&.
.SS "\fBNAClefSelect::~NAClefSelect\fP ()"
.PP
Definition at line 11 of file naclefselect\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "QString \fBNAClefSelect::clefS\fP"
.PP
Definition at line 24 of file naclefselect\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Notatio Antiqua from the source code\&.
