.TH "nadoinit" 3 "Tue Jun 12 2012" "Version 1.0.0.3164pre" "Notatio Antiqua" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nadoinit \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nadoinit\&.h>\fP
.SS "Signals"

.in +1c
.ti -1c
.RI "QString \fBpathHasChanged\fP (QString path)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetValues\fP (QString path)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QStringList \fBLaTeX_Path\fP"
.br
.ti -1c
.RI "QStringList \fBGregorio_Path\fP"
.br
.ti -1c
.RI "QStringList \fBLilypond_Path\fP"
.br
.ti -1c
.RI "QStringList \fBtemplateFolder\fP"
.br
.ti -1c
.RI "QStringList \fBdictFolder\fP"
.br
.ti -1c
.RI "QStringList \fBhelpFolder\fP"
.br
.ti -1c
.RI "QString \fBbasePath\fP"
.br
.ti -1c
.RI "QString \fBcurrentPath\fP"
.br
.ti -1c
.RI "QString \fBendText\fP"
.br
.ti -1c
.RI "bool \fBisinit\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 8 of file nadoinit\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "QString \fBnadoinit::pathHasChanged\fP (QStringpath)\fC [signal]\fP"
.SS "void \fBnadoinit::setValues\fP (QStringpath)"
.SH "Member Data Documentation"
.PP 
.SS "QString \fBnadoinit::basePath\fP"
.PP
Definition at line 15 of file nadoinit\&.h\&.
.SS "QString \fBnadoinit::currentPath\fP"
.PP
Definition at line 15 of file nadoinit\&.h\&.
.SS "QStringList \fBnadoinit::dictFolder\fP"
.PP
Definition at line 14 of file nadoinit\&.h\&.
.SS "QString \fBnadoinit::endText\fP"
.PP
Definition at line 15 of file nadoinit\&.h\&.
.SS "QStringList \fBnadoinit::Gregorio_Path\fP"
.PP
Definition at line 14 of file nadoinit\&.h\&.
.SS "QStringList \fBnadoinit::helpFolder\fP"
.PP
Definition at line 14 of file nadoinit\&.h\&.
.SS "bool \fBnadoinit::isinit\fP"
.PP
Definition at line 16 of file nadoinit\&.h\&.
.SS "QStringList \fBnadoinit::LaTeX_Path\fP"
.PP
Definition at line 14 of file nadoinit\&.h\&.
.SS "QStringList \fBnadoinit::Lilypond_Path\fP"
.PP
Definition at line 14 of file nadoinit\&.h\&.
.SS "QStringList \fBnadoinit::templateFolder\fP"
.PP
Definition at line 14 of file nadoinit\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Notatio Antiqua from the source code\&.
