.TH "NAHelp" 3 "Tue Jun 12 2012" "Version 1.0.0.3164pre" "Notatio Antiqua" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NAHelp \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nahelp\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNAHelp\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "\fB~NAHelp\fP ()"
.br
.ti -1c
.RI "void \fBcreateWidgets\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 18 of file nahelp\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBNAHelp::NAHelp\fP (QWidget *parent = \fC0\fP)\fC [explicit]\fP"
.PP
Definition at line 5 of file nahelp\&.cpp\&.
.SS "\fBNAHelp::~NAHelp\fP ()"
.PP
Definition at line 14 of file nahelp\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void \fBNAHelp::createWidgets\fP ()"
.PP
Definition at line 19 of file nahelp\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Notatio Antiqua from the source code\&.
