.TH "NAHeaderWizard" 3 "Tue Jun 12 2012" "Version 1.0.0.3164pre" "Notatio Antiqua" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NAHeaderWizard \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <naheaderwizard\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNAHeaderWizard\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "\fB~NAHeaderWizard\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QStringList \fBheader\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 19 of file naheaderwizard\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBNAHeaderWizard::NAHeaderWizard\fP (QWidget *parent = \fC0\fP)\fC [explicit]\fP"
.PP
Definition at line 4 of file naheaderwizard\&.cpp\&.
.SS "\fBNAHeaderWizard::~NAHeaderWizard\fP ()"
.PP
Definition at line 11 of file naheaderwizard\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "QStringList \fBNAHeaderWizard::header\fP"
.PP
Definition at line 26 of file naheaderwizard\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Notatio Antiqua from the source code\&.
