.TH "nainit" 3 "Tue Jun 12 2012" "Version 1.0.0.3164pre" "Notatio Antiqua" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nainit \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nainit\&.h>\fP
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBgetPath\fP (QString path)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBnainit\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "\fB~nainit\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBnadoinit\fP \fBdoinit\fP"
.br
.ti -1c
.RI "QString \fBLaTeX_Path\fP"
.br
.ti -1c
.RI "QString \fBGregorio_Path\fP"
.br
.ti -1c
.RI "QString \fBLilypond_Path\fP"
.br
.ti -1c
.RI "QString \fBtemplateFolder\fP"
.br
.ti -1c
.RI "QString \fBdictFolder\fP"
.br
.ti -1c
.RI "QString \fBhelpFolder\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 12 of file nainit\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBnainit::nainit\fP (QWidget *parent = \fC0\fP)\fC [explicit]\fP"
.PP
Definition at line 4 of file nainit\&.cpp\&.
.SS "\fBnainit::~nainit\fP ()"
.PP
Definition at line 11 of file nainit\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void \fBnainit::getPath\fP (QStringpath)\fC [slot]\fP"
.PP
Definition at line 40 of file nainit\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "QString \fBnainit::dictFolder\fP"
.PP
Definition at line 20 of file nainit\&.h\&.
.SS "\fBnadoinit\fP \fBnainit::doinit\fP"
.PP
Definition at line 19 of file nainit\&.h\&.
.SS "QString \fBnainit::Gregorio_Path\fP"
.PP
Definition at line 20 of file nainit\&.h\&.
.SS "QString \fBnainit::helpFolder\fP"
.PP
Definition at line 20 of file nainit\&.h\&.
.SS "QString \fBnainit::LaTeX_Path\fP"
.PP
Definition at line 20 of file nainit\&.h\&.
.SS "QString \fBnainit::Lilypond_Path\fP"
.PP
Definition at line 20 of file nainit\&.h\&.
.SS "QString \fBnainit::templateFolder\fP"
.PP
Definition at line 20 of file nainit\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Notatio Antiqua from the source code\&.
