.TH "NaProg" 3 "Tue Jun 12 2012" "Version 1.0.0.3164pre" "Notatio Antiqua" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NaProg \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <naprog\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNaProg\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "\fB~NaProg\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBQHeaderInfo\fP \fBhi\fP"
.br
.ti -1c
.RI "QProcess * \fBexecProg\fP"
.br
.ti -1c
.RI "QString \fBLaTeX_Path\fP"
.br
.ti -1c
.RI "QString \fBLilypond_Path\fP"
.br
.ti -1c
.RI "QString \fBGregorio_Path\fP"
.br
.ti -1c
.RI "QString \fBtmplName\fP"
.br
.ti -1c
.RI "QString \fBtemplateFolder\fP"
.br
.ti -1c
.RI "QString \fBdictFolder\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBchangeEvent\fP (QEvent *e)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 91 of file naprog\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBNaProg::NaProg\fP (QWidget *parent = \fC0\fP)"
.PP
Definition at line 19 of file naprog\&.cpp\&.
.SS "\fBNaProg::~NaProg\fP ()"
.PP
Definition at line 33 of file naprog\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void \fBNaProg::changeEvent\fP (QEvent *e)\fC [protected]\fP"
.PP
Definition at line 59 of file naprog\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "QString \fBNaProg::dictFolder\fP"
.PP
Definition at line 103 of file naprog\&.h\&.
.SS "QProcess* \fBNaProg::execProg\fP"
.PP
Definition at line 97 of file naprog\&.h\&.
.SS "QString \fBNaProg::Gregorio_Path\fP"
.PP
Definition at line 100 of file naprog\&.h\&.
.SS "\fBQHeaderInfo\fP \fBNaProg::hi\fP"
.PP
Definition at line 96 of file naprog\&.h\&.
.SS "QString \fBNaProg::LaTeX_Path\fP"
.PP
Definition at line 98 of file naprog\&.h\&.
.SS "QString \fBNaProg::Lilypond_Path\fP"
.PP
Definition at line 99 of file naprog\&.h\&.
.SS "QString \fBNaProg::templateFolder\fP"
.PP
Definition at line 102 of file naprog\&.h\&.
.SS "QString \fBNaProg::tmplName\fP"
.PP
Definition at line 101 of file naprog\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Notatio Antiqua from the source code\&.
