.TH "napsalm.h" 3 "Tue Jun 12 2012" "Version 1.0.0.3164pre" "Notatio Antiqua" \" -*- nroff -*-
.ad l
.nh
.SH NAME
napsalm.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QFrame>\fP
.br
\fC#include <QTextStream>\fP
.br
\fC#include <QMultiMap>\fP
.br
\fC#include <QDesktopServices>\fP
.br
\fC#include <QFile>\fP
.br
\fC#include <QMessageBox>\fP
.br
\fC#include <QSettings>\fP
.br
\fC#include <QFileDialog>\fP
.br
\fC#include 'hyphen\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBnapsalm\fP"
.br
.ti -1c
.RI "struct \fBnapsalm::NaPsalmTone\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBUi\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Notatio Antiqua from the source code\&.
