.TH "napsalm" 3 "Tue Jun 12 2012" "Version 1.0.0.3164pre" "Notatio Antiqua" \" -*- nroff -*-
.ad l
.nh
.SH NAME
napsalm \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <napsalm\&.h>\fP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBNaPsalmTone\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBnapsalm\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "\fB~napsalm\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 18 of file napsalm\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBnapsalm::napsalm\fP (QWidget *parent = \fC0\fP)\fC [explicit]\fP"
.PP
Definition at line 5 of file napsalm\&.cpp\&.
.SS "\fBnapsalm::~napsalm\fP ()"
.PP
Definition at line 13 of file napsalm\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Notatio Antiqua from the source code\&.
