.TH "napsalm.cpp" 3 "Tue Jun 12 2012" "Version 1.0.0.3164pre" "Notatio Antiqua" \" -*- nroff -*-
.ad l
.nh
.SH NAME
napsalm.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'napsalm\&.h'\fP
.br
\fC#include 'ui_napsalm\&.h'\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBBUFSIZE\fP   1000"
.br
.ti -1c
.RI "#define \fBQT_USE_FAST_CONCATENATION\fP"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define \fBBUFSIZE\fP   1000"
.PP
Definition at line 3 of file napsalm\&.cpp\&.
.SS "#define \fBQT_USE_FAST_CONCATENATION\fP"
.PP
Definition at line 4 of file napsalm\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Notatio Antiqua from the source code\&.
