.TH "nasettings.cpp" 3 "Tue Jun 12 2012" "Version 1.0.0.3164pre" "Notatio Antiqua" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nasettings.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QtDebug>\fP
.br
\fC#include <QDesktopServices>\fP
.br
\fC#include 'nasettings\&.h'\fP
.br
\fC#include 'ui_nasettings\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Notatio Antiqua from the source code\&.
