.TH "NASettings" 3 "Tue Jun 12 2012" "Version 1.0.0.3164pre" "Notatio Antiqua" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NASettings \- 
.PP
Settings class, holds some variables for the settings dialog and the dialog itself\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nasettings\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNASettings\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "\fB~NASettings\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QColor \fBkeyword\fP"
.br
.ti -1c
.RI "QColor \fBcommentary\fP"
.br
.ti -1c
.RI "QColor \fBpitch\fP"
.br
.ti -1c
.RI "QColor \fBtranslation\fP"
.br
.ti -1c
.RI "QString \fBfontsize\fP"
.br
.ti -1c
.RI "QString \fBstaffsize\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBchangeEvent\fP (QEvent *e)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Settings class, holds some variables for the settings dialog and the dialog itself\&. 
.PP
Definition at line 24 of file nasettings\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBNASettings::NASettings\fP (QWidget *parent = \fC0\fP)"
.PP
Definition at line 15 of file nasettings\&.cpp\&.
.SS "\fBNASettings::~NASettings\fP ()"
.PP
Definition at line 58 of file nasettings\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void \fBNASettings::changeEvent\fP (QEvent *e)\fC [protected]\fP"
.PP
Definition at line 63 of file nasettings\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "QColor \fBNASettings::commentary\fP"
.PP
Definition at line 34 of file nasettings\&.h\&.
.SS "QString \fBNASettings::fontsize\fP"
.PP
Definition at line 37 of file nasettings\&.h\&.
.SS "QColor \fBNASettings::keyword\fP"
.PP
Definition at line 33 of file nasettings\&.h\&.
.SS "QColor \fBNASettings::pitch\fP"
.PP
Definition at line 35 of file nasettings\&.h\&.
.SS "QString \fBNASettings::staffsize\fP"
.PP
Definition at line 38 of file nasettings\&.h\&.
.SS "QColor \fBNASettings::translation\fP"
.PP
Definition at line 36 of file nasettings\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Notatio Antiqua from the source code\&.
