.TH "nasettings.h" 3 "Tue Jun 12 2012" "Version 1.0.0.3164pre" "Notatio Antiqua" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nasettings.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QDialog>\fP
.br
\fC#include <QColor>\fP
.br
\fC#include <QColorDialog>\fP
.br
\fC#include <QSettings>\fP
.br
\fC#include <QMessageBox>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBNASettings\fP"
.br
.RI "\fISettings class, holds some variables for the settings dialog and the dialog itself\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBUi\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Notatio Antiqua from the source code\&.
