.TH "nasyntax.cpp" 3 "Tue Jun 12 2012" "Version 1.0.0.3164pre" "Notatio Antiqua" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nasyntax.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QtGui>\fP
.br
\fC#include 'nasyntax\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Notatio Antiqua from the source code\&.
