.TH "naview.h" 3 "Tue Jun 12 2012" "Version 1.0.0.3164pre" "Notatio Antiqua" \" -*- nroff -*-
.ad l
.nh
.SH NAME
naview.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QDialog>\fP
.br
\fC#include <QFile>\fP
.br
\fC#include <QDesktopServices>\fP
.br
\fC#include <QUrl>\fP
.br
\fC#include 'poppler-qt4\&.h'\fP
.br
\fC#include <QMessageBox>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBNaView\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBUi\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Notatio Antiqua from the source code\&.
