.TH "NaView" 3 "Tue Jun 12 2012" "Version 1.0.0.3164pre" "Notatio Antiqua" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NaView \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <naview\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNaView\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "\fB~NaView\fP ()"
.br
.ti -1c
.RI "int \fBrenderPDF\fP (int page)"
.br
.ti -1c
.RI "int \fBloadPDF\fP (QString filename)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QByteArray \fBpdfBA\fP"
.br
.ti -1c
.RI "QUrl \fBfileUrl\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 15 of file naview\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBNaView::NaView\fP (QWidget *parent = \fC0\fP)\fC [explicit]\fP"
.PP
Definition at line 4 of file naview\&.cpp\&.
.SS "\fBNaView::~NaView\fP ()"
.PP
Definition at line 11 of file naview\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "int \fBNaView::loadPDF\fP (QStringfilename)"
.PP
Definition at line 15 of file naview\&.cpp\&.
.SS "int \fBNaView::renderPDF\fP (intpage)"
.PP
Definition at line 29 of file naview\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "QUrl \fBNaView::fileUrl\fP"
.PP
Definition at line 25 of file naview\&.h\&.
.SS "QByteArray \fBNaView::pdfBA\fP"
.PP
Definition at line 24 of file naview\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Notatio Antiqua from the source code\&.
