.TH "QHeaderInfo" 3 "Tue Jun 12 2012" "Version 1.0.0.3164pre" "Notatio Antiqua" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QHeaderInfo \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <naprog\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QString \fBname\fP"
.br
.RI "\fI\fBQHeaderInfo\fP holds the parts of the GABC file header\&. \fP"
.ti -1c
.RI "QString \fBarranger\fP"
.br
.ti -1c
.RI "QString \fBofficepart\fP"
.br
.ti -1c
.RI "QString \fBmode\fP"
.br
.ti -1c
.RI "QString \fBannotation1\fP"
.br
.ti -1c
.RI "QString \fBannotation2\fP"
.br
.ti -1c
.RI "QString \fBcommentary\fP"
.br
.ti -1c
.RI "QString \fBfont\fP"
.br
.ti -1c
.RI "QString \fBgabccopy\fP"
.br
.ti -1c
.RI "QString \fBscorecopy\fP"
.br
.ti -1c
.RI "QString \fBoccasion\fP"
.br
.ti -1c
.RI "QString \fBmeter\fP"
.br
.ti -1c
.RI "QString \fBauthor\fP"
.br
.ti -1c
.RI "QString \fBdate\fP"
.br
.ti -1c
.RI "QString \fBmanuscript\fP"
.br
.ti -1c
.RI "QString \fBmreference\fP"
.br
.ti -1c
.RI "QString \fBbook\fP"
.br
.ti -1c
.RI "QString \fBtranscriber\fP"
.br
.ti -1c
.RI "QString \fBtdate\fP"
.br
.ti -1c
.RI "QString \fBinstyle\fP"
.br
.ti -1c
.RI "QString \fBnotes\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 62 of file naprog\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "QString \fBQHeaderInfo::annotation1\fP"
.PP
Definition at line 72 of file naprog\&.h\&.
.SS "QString \fBQHeaderInfo::annotation2\fP"
.PP
Definition at line 73 of file naprog\&.h\&.
.SS "QString \fBQHeaderInfo::arranger\fP"
.PP
Definition at line 69 of file naprog\&.h\&.
.SS "QString \fBQHeaderInfo::author\fP"
.PP
Definition at line 80 of file naprog\&.h\&.
.SS "QString \fBQHeaderInfo::book\fP"
.PP
Definition at line 84 of file naprog\&.h\&.
.SS "QString \fBQHeaderInfo::commentary\fP"
.PP
Definition at line 74 of file naprog\&.h\&.
.SS "QString \fBQHeaderInfo::date\fP"
.PP
Definition at line 81 of file naprog\&.h\&.
.SS "QString \fBQHeaderInfo::font\fP"
.PP
Definition at line 75 of file naprog\&.h\&.
.SS "QString \fBQHeaderInfo::gabccopy\fP"
.PP
Definition at line 76 of file naprog\&.h\&.
.SS "QString \fBQHeaderInfo::instyle\fP"
.PP
Definition at line 87 of file naprog\&.h\&.
.SS "QString \fBQHeaderInfo::manuscript\fP"
.PP
Definition at line 82 of file naprog\&.h\&.
.SS "QString \fBQHeaderInfo::meter\fP"
.PP
Definition at line 79 of file naprog\&.h\&.
.SS "QString \fBQHeaderInfo::mode\fP"
.PP
Definition at line 71 of file naprog\&.h\&.
.SS "QString \fBQHeaderInfo::mreference\fP"
.PP
Definition at line 83 of file naprog\&.h\&.
.SS "QString \fBQHeaderInfo::name\fP"
.PP
\fBQHeaderInfo\fP holds the parts of the GABC file header\&. 
.PP
Definition at line 68 of file naprog\&.h\&.
.SS "QString \fBQHeaderInfo::notes\fP"
.PP
Definition at line 88 of file naprog\&.h\&.
.SS "QString \fBQHeaderInfo::occasion\fP"
.PP
Definition at line 78 of file naprog\&.h\&.
.SS "QString \fBQHeaderInfo::officepart\fP"
.PP
Definition at line 70 of file naprog\&.h\&.
.SS "QString \fBQHeaderInfo::scorecopy\fP"
.PP
Definition at line 77 of file naprog\&.h\&.
.SS "QString \fBQHeaderInfo::tdate\fP"
.PP
Definition at line 86 of file naprog\&.h\&.
.SS "QString \fBQHeaderInfo::transcriber\fP"
.PP
Definition at line 85 of file naprog\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Notatio Antiqua from the source code\&.
