.TH "QHelpBrowser" 3 "Tue Jun 12 2012" "Version 1.0.0.3164pre" "Notatio Antiqua" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QHelpBrowser \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nahelp\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQHelpBrowser\fP (QString collectionFile, QWidget *parent)"
.br
.ti -1c
.RI "void \fBshowHelpForKeyword\fP (const QString &id)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 35 of file nahelp\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBQHelpBrowser::QHelpBrowser\fP (QStringcollectionFile, QWidget *parent)"
.PP
Definition at line 80 of file nahelp\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void \fBQHelpBrowser::showHelpForKeyword\fP (const QString &id)"
.PP
Definition at line 100 of file nahelp\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Notatio Antiqua from the source code\&.
