.TH "Version" 3 "Tue Jun 12 2012" "Version 1.0.0.3164pre" "Notatio Antiqua" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Version \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "const char * \fBversionString\fP ()"
.br
.ti -1c
.RI "const char * \fBglobalRevision\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const int \fBMAJOR\fP = 1"
.br
.ti -1c
.RI "const int \fBMINOR\fP = 0"
.br
.ti -1c
.RI "const int \fBLOCAL_REVISION\fP = 0"
.br
.ti -1c
.RI "const int \fBBUILD\fP = 3164"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "const char* \fBVersion::globalRevision\fP ()\fC [inline]\fP"
.PP
Definition at line 16 of file version\&.h\&.
.SS "const char* \fBVersion::versionString\fP ()\fC [inline]\fP"
.PP
Definition at line 11 of file version\&.h\&.
.SH "Variable Documentation"
.PP 
.SS "const int \fBVersion::BUILD\fP = 3164"
.PP
Definition at line 9 of file version\&.h\&.
.SS "const int \fBVersion::LOCAL_REVISION\fP = 0"
.PP
Definition at line 8 of file version\&.h\&.
.SS "const int \fBVersion::MAJOR\fP = 1"
.PP
Definition at line 6 of file version\&.h\&.
.SS "const int \fBVersion::MINOR\fP = 0"
.PP
Definition at line 7 of file version\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Notatio Antiqua from the source code\&.
