.TH "version.h" 3 "Tue Jun 12 2012" "Version 1.0.0.3164pre" "Notatio Antiqua" \" -*- nroff -*-
.ad l
.nh
.SH NAME
version.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBVersion\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "const char * \fBVersion::versionString\fP ()"
.br
.ti -1c
.RI "const char * \fBVersion::globalRevision\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const int \fBVersion::MAJOR\fP = 1"
.br
.ti -1c
.RI "const int \fBVersion::MINOR\fP = 0"
.br
.ti -1c
.RI "const int \fBVersion::LOCAL_REVISION\fP = 0"
.br
.ti -1c
.RI "const int \fBVersion::BUILD\fP = 3164"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Notatio Antiqua from the source code\&.
